# Configuración de la aplicación de Spring Boot
#y se registra en el servidor de eureka de docker "eureka-server"
#al usar contenedores de docker, se debe empaquetar sin pruebas .\mvnw clean package -DskipTests

spring:
  application:
    name: cjava-cursos

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://s9-eureka-server:8761/eureka/
